# Service identity
name: transceiver
author: vu-ase
source: https://github.com/VU-ASE/transceiver
version: 1.0.0

commands:
  build: make build 
  run: ./bin/transceiver

# No 'official' dependencies, but the transceiver listens to all streams from all services
inputs: []
outputs:
  - tuning # outputs all tuning messages received from the passthrough service, so that other services can listen and use them

configuration:
  - name: passthrough-address # address of the passthrough service
    value: localhost:8080